server:
  application:
    name: chathack
  port: 8080

spring:
  data:
    redis:
      repositoroes:
        enabled: false
  cache:
    type: redis
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
openai:
  OPENAI_API_KEY: aaa